common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rad
  password:
  host: localhost
  port: 5432

development:
  <<: *common
  database: oyf_development

test:
  <<: *common
  database: oyf_test

production:
  <<: *common
  database: oyf_production
